_wandb:
    value:
        cli_version: 0.23.1
        code_path: code/src/train_ppo.py
        e:
            0zloomvt644iwd48rkmw9l7vagiad637:
                codePath: src/train_ppo.py
                codePathLocal: src/train_ppo.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1967317549056"
                        used: "1207433084928"
                email: tj.vitchutripop@yale.edu
                executable: /data/tj/Documents/cv-project/.venv/bin/python3
                gpu: NVIDIA RTX 5000 Ada Generation
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-8b1deb60-a8af-3b4a-55f0-81321be6e7b7
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-6ec1b85f-79c3-c1fe-b004-0a916b2eb885
                host: xiatao-Lambda-Vector
                memory:
                    total: "269725433856"
                os: Linux-6.8.0-88-generic-x86_64-with-glibc2.39
                program: /data/tj/Documents/cv-project/src/train_ppo.py
                python: CPython 3.10.19
                root: /data/tj/Documents/cv-project
                startedAt: "2025-12-13T21:27:00.679758Z"
                writerId: 0zloomvt644iwd48rkmw9l7vagiad637
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 49
            "2":
                - 1
                - 49
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
anneal_lr:
    value: false
batch_size:
    value: 25600
capture_video:
    value: true
checkpoint:
    value: null
clip_coef:
    value: 0.2
clip_vloss:
    value: false
control_mode:
    value: pd_joint_delta_pos
cuda:
    value: true
depth:
    value: false
ent_coef:
    value: 0
env_cfg:
    value:
        control_mode: pd_joint_delta_pos
        env_horizon: 50
        env_id: PickCube-v1
        num_envs: 512
        obs_mode: rgb
        partial_reset: true
        render_mode: all
        reward_mode: normalized_dense
        sim_backend: physx_cuda
env_id:
    value: PickCube-v1
eval_env_cfg:
    value:
        control_mode: pd_joint_delta_pos
        env_horizon: 50
        env_id: PickCube-v1
        num_envs: 8
        obs_mode: rgb
        partial_reset: true
        render_mode: all
        reward_mode: normalized_dense
        sim_backend: physx_cuda
eval_freq:
    value: 25
eval_partial_reset:
    value: false
eval_reconfiguration_freq:
    value: 1
evaluate:
    value: false
exp_name:
    value: train_ppo
finite_horizon_gae:
    value: false
gae_lambda:
    value: 0.9
gamma:
    value: 0.8
include_state:
    value: true
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 800
norm_adv:
    value: true
num_envs:
    value: 512
num_eval_envs:
    value: 8
num_eval_steps:
    value: 50
num_iterations:
    value: 390
num_minibatches:
    value: 32
num_steps:
    value: 50
partial_reset:
    value: true
reconfiguration_freq:
    value: null
render_mode:
    value: all
reward_scale:
    value: 1
rgb:
    value: true
save_model:
    value: true
save_train_video_freq:
    value: null
seed:
    value: 1
target_kl:
    value: 0.2
torch_deterministic:
    value: true
total_timesteps:
    value: 10000000
track:
    value: true
update_epochs:
    value: 4
vf_coef:
    value: 0.5
wandb_entity:
    value: null
wandb_group:
    value: PPO
wandb_project_name:
    value: vision-rl
